### ISSUE TITLE
last.fm plugin seems to publish api key in the commit message?

### ISSUE THREAD

**Issue by carlosalonso** [commandline/flashbake#14]
I tried to use the last.fm plugin, but when running flashbake -c the API call, including my API key is published as the 1st line of the commit message.

**Comment by ianpaul** [comment]
This comment is stale, but since it's here...I think an easy solution is to just delete the `logging.info` command on line 43. That's how it's being captured as far as I can tell. Is that okay with you @commandline or is there a better alternative?

**Comment by commandline** [comment]
Changing it to debug, I think, would be preferable.

**Comment by ianpaul** [comment]
Sounds good. Pull request sent.

**Comment by ianpaul** [comment]
bumping this for @commandline with a request to close as this is resolved.
