### ISSUE TITLE
Modified files get not recognized

### ISSUE THREAD

**Issue by christianlupus** [commandline/flashbake#20]
Hello,

I just tried flashbake using my ubuntu 14.04LTS. The effect was - well - catastrophic. Flashbake did not recognize any modifications of any file. Thus I installed the most recent version from github but without success.

A bit more verbose:

- Create a new folder. Create a git repo therein (`git init`).
- Create a dummy config file. In my case it was just

> plugins:flashbake.plugins.timezone:TimeZone
> a
> \# b

- Create the file "a" and do a `flashbake` on the directory. The file gets checked in (ok so far).
- Create a second file "b" and uncomment in the config file. Using `flashbake` it gets checked in.
- Modify either file. `git status` shows the modifications clearly. When I apply `flashbreak` I get the message that no constent to be checked in has changed. (???)

Please note a small "bug": You seem to parse the output of git in some sense. If the user has a different language than English, you get into trouble. In this case (I am German) flashbreak did not even check in the very first version. I had to manually `export LANG=C` before. Maybe you might alter the LANG environment variable on calling git such that English is always used.

Hope this helps.
Christian Wolf

**Comment by grantdobbe** [comment]
Can confirm. This also resolves an issue with globs not working in nested directories.

**Comment by commandline** [comment]
This is likely a consequence of my ignorance to git porcelain, where output would be less subject to change and hence more amenable to parsing. If I ever get time to work on this repo in earnest, I would drop the custom output processing altogether anyway. I'll make this change and cut a new release.

**Comment by commandline** [comment]
OK, cut 0.27.1 if all/any of you want to grab, test, and then feel free to close this issue.

**Comment by grantdobbe** [comment]
Pulled and tested this evening. Works as advertised. Thanks, Thomas!
