### ISSUE TITLE
http://bitbucketlabs.net/flashbake/ is 404?

### ISSUE THREAD

**Issue by shanselman** [commandline/flashbake#21]
http://bitbucketlabs.net/flashbake/ is 404?

**Comment by commandline** [comment]
I let the domain lapse because I wasn't really doing anything with it. Is there a link to it in this repo? It has been so long that I've done anything with this project I honestly cannot recall.

**Comment by xtaran** [comment]
Yes and no. It's not in the repo but in its meta data behind the small description on top of the file listing at https://github.com/commandline/flashbake

**Comment by commandline** [comment]
OK, I'll try to make time to sort this out in the next little bit.

**Comment by rhinux** [comment]
http://bitbucketlabs.net/flashbake/ is used in **debian description** for the package.

**Comment by xtaran** [comment]
@rhinux: Not only. It is still used on top of https://github.com/commandline/flashbake/ -- which IMHO should be fixed _first_.

**Comment by commandline** [comment]
Should be fixed.
