### ISSUE TITLE
Move away from enum library

### ISSUE THREAD

**Issue by FedericoCeratto** [commandline/flashbake#22]
The Enum https://pypi.python.org/pypi/enum/ library is not maintained anymore and I'm considering removing it from Debian. Would you consider switching to https://pypi.python.org/pypi/enum34 ?
Thanks

**Comment by xtaran** [comment]
That'd be nice indeed. flashbake is already no more co-installable on Debian Unstable with anything that already uses the enum34 library (too many tools to list manually).

**Comment by commandline** [comment]
Will try to make time for this but also happy to accept a pull request.

**Comment by FedericoCeratto** [comment]
(related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795444)
